[WIP] APPS-306: Payment API improvements
spryker-eco/payone pull request #61
Opened 2021-04-09 18:00 UTC by olehnovatskyi-spryker

Temporary text

2021-04-13 11:40 UTC, oleksander-kiiashko approved these changes

2021-04-14 11:51 UTC, matweew requested changes

2021-04-14 11:51 UTC, matweew commented on tests/SprykerEcoTest/Zed/Payone/_support/_generated/PayoneZedTesterActions.php
> +<?php  //[STAMP] 44c949f5ab6d2d78611c50300791b34e
please remove, it's generated one

2021-04-14 11:51 UTC, matweew commented on src/SprykerEco/Zed/Payone/Communication/Plugin/Checkout/PayoneCheckoutPostSavePlugin.php
> +use Spryker\Zed\CheckoutExtension\Dependency\Plugin\CheckoutPostSaveInterface;
this interface requires new version of "spryker/checkout-extension" which is absent in composer.json

2021-04-14 11:51 UTC, matweew commented on tests/SprykerEcoTest/Zed/Payone/Business/Order/SaveOrderTest.php
> +    public function testSaveOrderPayment()
```suggestion
    public function testSaveOrderPaymentStoresCorrectOrderPayment()
```

2021-04-20 11:50 UTC, olehnovatskyi-spryker commented on src/SprykerEco/Zed/Payone/Business/Payment/PaymentManager.php
> +        }
discussed

2021-04-27 09:27 UTC, matweew commented
also please try to switch to GitHub Actions (example https://github.com/spryker-eco/after-pay/pull/23/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f)

and remove .travis.yml

the goal to execute `phpcs` and if possible `phpstan`

2021-04-27 12:41 UTC, matweew commented on tests/SprykerEcoTest/Yves/Payone/_support/_generated/PayoneYvesTesterActions.php
> +<?php  //[STAMP] 78f011b48081081169267cd48d746928
and add `tests/**/_generated/` to .gitignore

2021-05-12 17:01 UTC, matweew approved these changes

2021-05-13 07:08 UTC, merged