CC-13920: Submit 'crefoPay' payment methods blocked by 'Payone' module
spryker-eco/payone pull request #70
Opened 2021-06-29 07:02 UTC by andrew-maslov

Ticket: https://spryker.atlassian.net/browse/CC-13920

2021-06-29 14:19 UTC, FRITS-Kh requested changes
Please add a changelog.

2021-06-29 14:19 UTC, FRITS-Kh commented on src/SprykerEco/Yves/Payone/Theme/default/components/molecules/payone-credit-card/payone-credit-card.ts
> +            debugger;
Please fix this part 😱

2021-07-01 08:51 UTC, FRITS-Kh approved these changes

2021-07-27 11:00 UTC, dmytro-sokolovskyi approved these changes

2021-08-03 10:17 UTC, merged