TE-9639 Fix exception during guest checkout
spryker-eco/payone pull request #73
Opened 2021-08-19 10:48 UTC by dmytro-dymarchuk

2021-08-19 14:23 UTC, olhalivitchuk commented on src/SprykerEco/Yves/Payone/Form/DataProvider/InstantOnlineTransferDataProvider.php
> +    private $storeClient;
shouldn't we use protected?

2021-08-19 14:25 UTC, olhalivitchuk commented on src/SprykerEco/Yves/Payone/Form/DirectDebitSubForm.php
> +        if ($currentCountry === 'DE') {
is it better to use something like protected const STORE_NAME = 'DE'; ?

2021-08-19 14:27 UTC, olhalivitchuk commented on src/SprykerEco/Zed/Payone/Business/Payment/MethodMapper/SecurityInvoice.php
>          return $paymentMethodContainer;
I guess we can avoid here of creating a variable

2021-08-19 14:29 UTC, olhalivitchuk commented on src/SprykerEco/Zed/Payone/Business/PayoneBusinessFactory.php
> +     * @deprecated
not informative

2021-08-19 14:30 UTC, olhalivitchuk commented on src/SprykerEco/Zed/Payone/Dependency/Facade/PayoneToStoreFacadeBridge.php
> +    private $storeFacade;
the same

2021-08-19 14:30 UTC, olhalivitchuk commented on src/SprykerEco/Zed/Payone/PayoneConfig.php
> +    public function getRequestStandardParameter(string $currencyIsoCode, string $countryIsoCode)
return type

2021-08-19 14:31 UTC, olhalivitchuk commented on src/SprykerEco/Zed/Payone/PayoneDependencyProvider.php
> +     * @deprecated
not informative

2021-08-19 14:34 UTC, olhalivitchuk commented on src/SprykerEco/Yves/Payone/Form/DataProvider/DirectDebitDataProvider.php
>      protected function getBankCountries()
return type is missed

2021-08-19 14:34 UTC, olhalivitchuk requested changes
some small comments

2021-08-30 08:07 UTC, dmytro-dymarchuk commented on src/SprykerEco/Zed/Payone/Dependency/Facade/PayoneToStoreFacadeBridge.php
> +    public function getCurrentStore()
Method signature in a bridge must be the same as an original facade.

2021-08-30 08:07 UTC, dmytro-dymarchuk commented on src/SprykerEco/Zed/Payone/Dependency/Facade/PayoneToStoreFacadeInterface.php
> +    public function getCurrentStore();
Method signature in a bridge must be the same as an original facade.

2021-08-30 10:08 UTC, olhalivitchuk commented on src/SprykerEco/Zed/Payone/Business/Payment/MethodMapper/Prepayment.php
>          return $paymentMethodContainer;
```suggestion
        return $paymentMethodContainer;
```

2021-08-30 10:12 UTC, olhalivitchuk approved these changes
approved with one small comment

2021-08-31 13:35 UTC, geega approved these changes

2021-08-31 14:47 UTC, merged